name: Python Code Quality

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install black ruff

      - name: Format
        run: black .

      - name: Commit formatting
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          if [[ `git status --porcelain` ]]; then
          git add .
          git commit -m "style: auto-format with black"
          git push
          fi

      - name: Lint
        run: ruff check . --output-format=github

      - name: Install type checker
        run: pip install mypy

      - name: Install tools
        run: |
          pip install mypy reviewdog

      - name: Run mypy with annotations
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mypy . --show-error-codes --no-color-output \
          | reviewdog -f=mypy -reporter=github-pr-check -level=error
